import AppPageShell from "@/components/app/AppPageShell";
import AdminOnlyPageGate from "@/components/discovery/AdminOnlyPageGate";
import GamesOfWeekView from "@/components/discovery/GamesOfWeekView";
import { resolveRotation } from "@/lib/discovery/rotation-store";
import type { WeeklyGamePick } from "@/lib/discovery/curated-picks";
import { buildPublicPageMetadata } from "@/lib/seo/site";
import type { Metadata } from "next";

export const metadata: Metadata = buildPublicPageMetadata({
  title: "Games worth checking this week | GamePing AI",
  description:
    "A weekly mix of standout deals, overlooked picks, and games that deserve your attention right now — with categories, a featured pick, and a curated grid.",
  path: "/games-of-the-week",
});

// Read fresh on each request so a newly published rotation shows immediately;
// the data comes from the cached Supabase rotation (no RAWG/ITAD per visit).
export const dynamic = "force-dynamic";

// Admin-only while incomplete. The page reads the latest *published* rotation
// from Supabase (cached, generated by /api/admin/discovery/generate). Fallback
// order: current published rotation → latest published rotation → static list.
// Everyone except admins is blocked by AdminOnlyPageGate.
export default async function GamesOfTheWeekPage() {
  const { data, meta } = await resolveRotation<WeeklyGamePick>("games_of_the_week");

  return (
    <AppPageShell hideAmbient>
      <div className="gp-accent-page relative isolate min-h-0 flex-1 overflow-hidden">
        {/* Fixed cinematic background — SAME image in light + dark. */}
        <div aria-hidden className="gp-gotw-bg" />
        <AdminOnlyPageGate>
          <GamesOfWeekView
            featured={data?.featured}
            picks={data?.picks}
            meta={meta ?? undefined}
          />
        </AdminOnlyPageGate>
      </div>
    </AppPageShell>
  );
}
