import AppPageShell from "@/components/app/AppPageShell";
import GamesOfWeekView from "@/components/discovery/GamesOfWeekView";
import { resolveRotation } from "@/lib/discovery/rotation-store";
import { resolvePremiumPageAccess } from "@/lib/discovery/premium-page-access";
import type { WeeklyGamePick } from "@/lib/discovery/curated-picks";
import { buildPublicPageMetadata } from "@/lib/seo/site";
import type { Metadata } from "next";

export const metadata: Metadata = buildPublicPageMetadata({
  title: "Games worth checking this week | GamePing AI",
  description:
    "A weekly mix of standout deals, overlooked picks, and games that deserve your attention right now — with categories, a featured pick, and a curated grid.",
  path: "/games-of-the-week",
});

// Read fresh on each request so a newly published rotation shows immediately;
// the data comes from the cached Supabase rotation (no RAWG/OpenAI per visit).
export const dynamic = "force-dynamic";

// Public page. Reads the cached *published* rotation from Supabase (generated by
// the discovery cron / admin route — never on a page visit). Fallback order:
// current published rotation → latest published rotation → static curated list.
export default async function GamesOfTheWeekPage() {
  const [{ data, meta }, access] = await Promise.all([
    resolveRotation<WeeklyGamePick>("games_of_the_week"),
    resolvePremiumPageAccess(),
  ]);

  return (
    <AppPageShell hideAmbient>
      <div className="gp-accent-page relative isolate min-h-0 flex-1 overflow-hidden">
        {/* Fixed cinematic background — SAME image in light + dark. */}
        <div aria-hidden className="gp-gotw-bg" />
        <GamesOfWeekView
          featured={data?.featured}
          picks={data?.picks}
          meta={meta ?? undefined}
          canViewWeeklyPicks={access.canViewPersonalized}
          breadcrumbs={[
            { label: "Home", href: "/" },
            { label: "Games of the week" },
          ]}
        />
      </div>
    </AppPageShell>
  );
}
