import { steamHeaderImage } from "@/lib/curated/game-links";

export type HomeGamePick = {
  title: string;
  /** Short genre or vibe label */
  tag: string;
  image: string;
};

/**
 * Alan Wake 2 is an Epic Games Store exclusive — it has NO Steam app id, so there
 * is no `steamHeaderImage()` for it and the one that used to sit here (1597180)
 * was invented: it 404s on the Steam CDN.
 *
 * This matters beyond the picture. `lib/pricing/steam-app-id.ts` harvests trusted
 * Steam app ids by regexing them back OUT of these image URLs, so a fake id here
 * became a fake "trusted" id for price lookups. A RAWG URL carries no app id, so
 * pricing correctly falls through to CheapShark/RAWG instead.
 */
const ALAN_WAKE_2_RAWG_IMAGE =
  "https://media.rawg.io/media/games/5b9/5b963d7633cd640fa2dbc4069d1c6377.jpg";

/**
 * Curated picks for the homepage carousel only — no API calls.
 * Images: Steam store headers (stable CDN URLs).
 */
export const HOME_CAROUSEL_PICKS: HomeGamePick[] = [
  {
    title: "Hades",
    tag: "Roguelike · Mythic action",
    image: steamHeaderImage(1145360),
  },
  {
    title: "Stardew Valley",
    tag: "Cozy · Farming sim",
    image: steamHeaderImage(413150),
  },
  {
    title: "Hollow Knight",
    tag: "Metroidvania · Atmospheric",
    image: steamHeaderImage(367520),
  },
  {
    title: "Disco Elysium",
    tag: "Narrative RPG · Choices",
    image: steamHeaderImage(632470),
  },
  {
    title: "Dead Cells",
    tag: "Roguelite · Fast combat",
    image: steamHeaderImage(588650),
  },
  {
    title: "Subnautica",
    tag: "Survival · Underwater",
    image: steamHeaderImage(264710),
  },
  {
    title: "Life is Strange",
    tag: "Story-driven · Emotional",
    image: steamHeaderImage(319630),
  },
  {
    title: "Terraria",
    tag: "Sandbox · Crafting",
    image: steamHeaderImage(105600),
  },
  {
    title: "The Forest",
    tag: "Survival · Horror",
    image: steamHeaderImage(242760),
  },
  {
    title: "Stranded Deep",
    tag: "Survival · Island",
    image: steamHeaderImage(313120),
  },
];

/** Extra picks for the homepage carousel pool only (deduped with `HOME_CAROUSEL_PICKS`). */
const HOME_CAROUSEL_EXTRAS: HomeGamePick[] = [
  { title: "Baldur's Gate 3", tag: "CRPG · Party choices", image: steamHeaderImage(1086940) },
  { title: "Celeste", tag: "Precision platformer · Indie", image: steamHeaderImage(504230) },
  { title: "Dave the Diver", tag: "Adventure · Restaurant sim", image: steamHeaderImage(1868140) },
  { title: "Deep Rock Galactic", tag: "Co-op FPS · Mining", image: steamHeaderImage(548430) },
  { title: "Elden Ring", tag: "Open world · Soulslike", image: steamHeaderImage(1245620) },
  { title: "Factorio", tag: "Automation · Factory sim", image: steamHeaderImage(427520) },
  { title: "Firewatch", tag: "Walking sim · Mystery", image: steamHeaderImage(383870) },
  { title: "It Takes Two", tag: "Co-op adventure · Platformer", image: steamHeaderImage(1426210) },
  { title: "Lethal Company", tag: "Co-op horror · Scavenging", image: steamHeaderImage(1966720) },
  { title: "Outer Wilds", tag: "Exploration puzzle · Sci-fi", image: steamHeaderImage(753640) },
  { title: "Ori and the Will of the Wisps", tag: "Metroidvania · Platformer", image: steamHeaderImage(1057090) },
  { title: "Portal 2", tag: "Puzzle · Comedy", image: steamHeaderImage(620) },
  { title: "Raft", tag: "Co-op survival · Ocean", image: steamHeaderImage(648800) },
  { title: "Risk of Rain 2", tag: "Co-op roguelike · Third person", image: steamHeaderImage(632360) },
  { title: "RimWorld", tag: "Colony sim · Story generator", image: steamHeaderImage(294100) },
  { title: "Slay the Spire", tag: "Roguelike deckbuilder", image: steamHeaderImage(646570) },
  { title: "Spiritfarer", tag: "Cozy management · Emotional", image: steamHeaderImage(972660) },
  { title: "The Binding of Isaac: Rebirth", tag: "Roguelike · Twin-stick", image: steamHeaderImage(250900) },
  { title: "The Witcher 3: Wild Hunt", tag: "Open-world RPG · Fantasy", image: steamHeaderImage(292030) },
  { title: "Titanfall 2", tag: "FPS campaign · Parkour", image: steamHeaderImage(1237970) },
  { title: "Undertale", tag: "Indie RPG · Quirky", image: steamHeaderImage(391540) },
  { title: "Valheim", tag: "Survival · Co-op Viking", image: steamHeaderImage(892970) },
  { title: "Vampire Survivors", tag: "Bullet heaven · Roguelike", image: steamHeaderImage(1794680) },
  { title: "Alan Wake 2", tag: "Survival horror · Narrative", image: ALAN_WAKE_2_RAWG_IMAGE },
  { title: "BioShock Infinite", tag: "FPS · Narrative steampunk", image: steamHeaderImage(8870) },
  { title: "Control", tag: "Third-person · Paranormal", image: steamHeaderImage(870780) },
  { title: "Cuphead", tag: "Run-and-gun · Boss rush", image: steamHeaderImage(268910) },
  { title: "DREDGE", tag: "Fishing adventure · Cosmic horror", image: steamHeaderImage(1562430) },
  { title: "Inscryption", tag: "Card roguelike · Horror", image: steamHeaderImage(1092790) },
  { title: "Inside", tag: "Puzzle platformer · Atmospheric", image: steamHeaderImage(304430) },
  { title: "Journey", tag: "Adventure · Wordless", image: steamHeaderImage(638230) },
  { title: "Mass Effect Legendary Edition", tag: "Sci-fi RPG trilogy", image: steamHeaderImage(1328670) },
  { title: "Monster Hunter: World", tag: "Action · Co-op hunts", image: steamHeaderImage(582010) },
  { title: "NieR:Automata", tag: "Action RPG · Hack and slash", image: steamHeaderImage(524220) },
  { title: "Persona 5 Royal", tag: "JRPG · Turn-based", image: steamHeaderImage(1687950) },
  { title: "Phasmophobia", tag: "Co-op horror · Investigation", image: steamHeaderImage(739630) },
  { title: "Project Zomboid", tag: "Survival · Zombie sandbox", image: steamHeaderImage(108600) },
  { title: "Resident Evil 4", tag: "Survival horror · Remake", image: steamHeaderImage(2050650) },
  { title: "Sekiro: Shadows Die Twice", tag: "Action · Stealth soulslike", image: steamHeaderImage(814380) },
  { title: "Slime Rancher", tag: "Cute farming · Exploration", image: steamHeaderImage(433340) },
  { title: "Two Point Hospital", tag: "Management sim · Comedy", image: steamHeaderImage(535930) },
  { title: "XCOM 2", tag: "Turn-based tactics · Sci-fi", image: steamHeaderImage(268500) },
  { title: "Yakuza: Like a Dragon", tag: "JRPG · Turn-based crime saga", image: steamHeaderImage(1235140) },
  { title: "DOOM Eternal", tag: "Fast FPS · Heavy metal", image: steamHeaderImage(782330) },
  { title: "HELLDIVERS 2", tag: "Co-op shooter · Sci-fi", image: steamHeaderImage(553850) },
  { title: "No Man's Sky", tag: "Exploration · Survival", image: steamHeaderImage(275850) },
  { title: "Palworld", tag: "Survival crafting · Creatures", image: steamHeaderImage(1623730) },
];

/**
 * Extra directory-only entries (well-known Steam titles; RAWG search usually resolves).
 * Merged with carousel picks for /games — deduped by title.
 */
const EXTRA_DIRECTORY_GAMES: HomeGamePick[] = [
  { title: "7 Days to Die", tag: "Survival crafting · Zombies", image: steamHeaderImage(251570) },
  { title: "Alan Wake 2", tag: "Survival horror · Narrative", image: ALAN_WAKE_2_RAWG_IMAGE },
  { title: "American Truck Simulator", tag: "Driving sim · Relaxation", image: steamHeaderImage(270880) },
  { title: "Among Us", tag: "Social deduction · Party", image: steamHeaderImage(945360) },
  { title: "ARK: Survival Evolved", tag: "Survival · Dinosaurs", image: steamHeaderImage(346110) },
  { title: "Assassin's Creed Odyssey", tag: "Open world · Action RPG", image: steamHeaderImage(812140) },
  { title: "Baldur's Gate 3", tag: "CRPG · Party choices", image: steamHeaderImage(1086940) },
  { title: "BioShock Infinite", tag: "FPS · Narrative steampunk", image: steamHeaderImage(8870) },
  { title: "Celeste", tag: "Precision platformer · Indie", image: steamHeaderImage(504230) },
  { title: "Control", tag: "Third-person · Paranormal", image: steamHeaderImage(870780) },
  { title: "Cult of the Lamb", tag: "Roguelike · Cult management", image: steamHeaderImage(1313140) },
  { title: "Cuphead", tag: "Run-and-gun · Boss rush", image: steamHeaderImage(268910) },
  { title: "Cyberpunk 2077", tag: "Sci-fi RPG · Open world", image: steamHeaderImage(1091500) },
  { title: "Dark Souls III", tag: "Action RPG · Soulslike", image: steamHeaderImage(374320) },
  { title: "Dave the Diver", tag: "Adventure · Restaurant sim", image: steamHeaderImage(1868140) },
  { title: "Death Stranding Director's Cut", tag: "Open world · Delivery", image: steamHeaderImage(1850570) },
  { title: "Deep Rock Galactic", tag: "Co-op FPS · Mining", image: steamHeaderImage(548430) },
  { title: "Devil May Cry 5", tag: "Stylish action · Hack and slash", image: steamHeaderImage(601150) },
  { title: "DOOM Eternal", tag: "Fast FPS · Heavy metal", image: steamHeaderImage(782330) },
  { title: "DREDGE", tag: "Fishing adventure · Cosmic horror", image: steamHeaderImage(1562430) },
  { title: "Elden Ring", tag: "Open world · Soulslike", image: steamHeaderImage(1245620) },
  { title: "Euro Truck Simulator 2", tag: "Driving sim · Relaxation", image: steamHeaderImage(227300) },
  { title: "Factorio", tag: "Automation · Factory sim", image: steamHeaderImage(427520) },
  { title: "Fallout: New Vegas", tag: "Open-world RPG · Post-apoc", image: steamHeaderImage(22380) },
  { title: "Firewatch", tag: "Walking sim · Mystery", image: steamHeaderImage(383870) },
  { title: "Ghost of Tsushima DIRECTOR'S CUT", tag: "Open world · Samurai", image: steamHeaderImage(2215430) },
  { title: "God of War", tag: "Action-adventure · Norse myth", image: steamHeaderImage(1593500) },
  { title: "Grand Theft Auto V", tag: "Open world · Action", image: steamHeaderImage(271590) },
  { title: "Half-Life 2", tag: "Classic FPS · Narrative", image: steamHeaderImage(220) },
  { title: "HELLDIVERS 2", tag: "Co-op shooter · Sci-fi", image: steamHeaderImage(553850) },
  { title: "Hogwarts Legacy", tag: "Open-world · Wizard RPG", image: steamHeaderImage(990080) },
  { title: "Horizon Zero Dawn Complete Edition", tag: "Open world · Action RPG", image: steamHeaderImage(1151640) },
  { title: "Left 4 Dead 2", tag: "Co-op · Zombie shooter", image: steamHeaderImage(550) },
  { title: "Lethal Company", tag: "Co-op horror · Scavenging", image: steamHeaderImage(1966720) },
  { title: "Mass Effect Legendary Edition", tag: "Sci-fi RPG trilogy", image: steamHeaderImage(1328670) },
  { title: "Minecraft", tag: "Sandbox · Survival creative", image: steamHeaderImage(1672970) },
  { title: "Monster Hunter: World", tag: "Action · Co-op hunts", image: steamHeaderImage(582010) },
  { title: "NieR:Automata", tag: "Action RPG · Hack and slash", image: steamHeaderImage(524220) },
  { title: "No Man's Sky", tag: "Exploration · Survival", image: steamHeaderImage(275850) },
  { title: "Outer Wilds", tag: "Exploration puzzle · Sci-fi", image: steamHeaderImage(753640) },
  { title: "Ori and the Will of the Wisps", tag: "Metroidvania · Platformer", image: steamHeaderImage(1057090) },
  { title: "Palworld", tag: "Survival crafting · Creatures", image: steamHeaderImage(1623730) },
  { title: "Persona 5 Royal", tag: "JRPG · Turn-based", image: steamHeaderImage(1687950) },
  { title: "Phasmophobia", tag: "Co-op horror · Investigation", image: steamHeaderImage(739630) },
  { title: "Portal 2", tag: "Puzzle · Comedy", image: steamHeaderImage(620) },
  { title: "Project Zomboid", tag: "Survival · Zombie sandbox", image: steamHeaderImage(108600) },
  { title: "Raft", tag: "Co-op survival · Ocean", image: steamHeaderImage(648800) },
  { title: "Red Dead Redemption 2", tag: "Open world · Western", image: steamHeaderImage(1174180) },
  { title: "Resident Evil 4", tag: "Survival horror · Remake", image: steamHeaderImage(2050650) },
  { title: "Risk of Rain 2", tag: "Co-op roguelike · Third person", image: steamHeaderImage(632360) },
  { title: "RimWorld", tag: "Colony sim · Story generator", image: steamHeaderImage(294100) },
  { title: "Rust", tag: "Survival multiplayer · PvP", image: steamHeaderImage(252490) },
  { title: "Sea of Thieves", tag: "Pirate sandbox · Co-op", image: steamHeaderImage(1172620) },
  { title: "Sekiro: Shadows Die Twice", tag: "Action · Stealth soulslike", image: steamHeaderImage(814380) },
  { title: "Slay the Spire", tag: "Roguelike deckbuilder", image: steamHeaderImage(646570) },
  { title: "Slime Rancher", tag: "Cute farming · Exploration", image: steamHeaderImage(433340) },
  { title: "Slime Rancher 2", tag: "Sequel · Cozy exploration", image: steamHeaderImage(1657630) },
  { title: "Spiritfarer", tag: "Cozy management · Emotional", image: steamHeaderImage(972660) },
  { title: "Starfield", tag: "Sci-fi RPG · Exploration", image: steamHeaderImage(1716740) },
  { title: "The Binding of Isaac: Rebirth", tag: "Roguelike · Twin-stick", image: steamHeaderImage(250900) },
  { title: "The Elder Scrolls V: Skyrim Special Edition", tag: "Open-world RPG", image: steamHeaderImage(489830) },
  { title: "The Last of Us Part I", tag: "Cinematic action-adventure", image: steamHeaderImage(1888930) },
  { title: "The Witcher 3: Wild Hunt", tag: "Open-world RPG · Fantasy", image: steamHeaderImage(292030) },
  { title: "Titanfall 2", tag: "FPS campaign · Parkour", image: steamHeaderImage(1237970) },
  { title: "Two Point Hospital", tag: "Management sim · Comedy", image: steamHeaderImage(535930) },
  { title: "Undertale", tag: "Indie RPG · Quirky", image: steamHeaderImage(391540) },
  { title: "Valheim", tag: "Survival · Co-op Viking", image: steamHeaderImage(892970) },
  { title: "Vampire Survivors", tag: "Bullet heaven · Roguelike", image: steamHeaderImage(1794680) },
  { title: "Cities: Skylines", tag: "City builder · Management", image: steamHeaderImage(255710) },
  // Sparse first-letter coverage for /games A–Z nav (I J K Q W X Y Z)
  { title: "Inscryption", tag: "Card roguelike · Horror", image: steamHeaderImage(1092790) },
  { title: "Inside", tag: "Puzzle platformer · Atmospheric", image: steamHeaderImage(304430) },
  { title: "It Takes Two", tag: "Co-op adventure · Platformer", image: steamHeaderImage(1426210) },
  { title: "Journey", tag: "Adventure · Wordless", image: steamHeaderImage(638230) },
  { title: "Jusant", tag: "Climbing puzzle · Meditative", image: steamHeaderImage(1977170) },
  { title: "Kerbal Space Program", tag: "Sandbox · Space sim", image: steamHeaderImage(220200) },
  {
    title: "Kingdom Come: Deliverance",
    tag: "Open-world RPG · Historical",
    image: steamHeaderImage(379430),
  },
  { title: "QUAKE", tag: "Classic FPS · Remaster", image: steamHeaderImage(2310) },
  { title: "Quantum Break", tag: "Third-person · Time powers", image: steamHeaderImage(474960) },
  { title: "Warframe", tag: "Co-op looter shooter · Sci-fi", image: steamHeaderImage(230410) },
  { title: "Witchfire", tag: "Roguelite FPS · Dark fantasy", image: steamHeaderImage(3156770) },
  { title: "XCOM 2", tag: "Turn-based tactics · Sci-fi", image: steamHeaderImage(268500) },
  { title: "Yakuza: Like a Dragon", tag: "JRPG · Turn-based crime saga", image: steamHeaderImage(1235140) },
  { title: "Zombie Army 4: Dead War", tag: "Co-op shooter · Horror", image: steamHeaderImage(694280) },
  {
    title: "Zero Escape: The Nonary Games",
    tag: "Visual novel · Escape room",
    image: steamHeaderImage(477740),
  },

  /* ── Games named by curated collections ──────────────────────────────
   * Added from the collections that already reference them. Every app id below was
   * checked against Steam (npm run verify:games) before it landed here: the pricing
   * layer trusts these image URLs to resolve a title to a Steam app, so a wrong one
   * would quietly show another game's price.
   */
  { title: "20 Minutes Till Dawn", tag: "Action · Adventure", image: steamHeaderImage(1966900) },
  { title: "A Plague Tale: Innocence", tag: "Action · Adventure", image: steamHeaderImage(752590) },
  { title: "A Short Hike", tag: "Adventure", image: steamHeaderImage(1055540) },
  { title: "A Way Out", tag: "Action · Adventure", image: steamHeaderImage(1222700) },
  { title: "Abzu", tag: "Adventure · Casual", image: steamHeaderImage(384190) },
  { title: "Age of Wonders 4", tag: "RPG · Strategy", image: steamHeaderImage(1669000) },
  { title: "Anno 1800", tag: "Simulation · Strategy", image: steamHeaderImage(916440) },
  { title: "Antichamber", tag: "Adventure", image: steamHeaderImage(219890) },
  { title: "art of rally", tag: "Action · Racing", image: steamHeaderImage(550320) },
  { title: "Astroneer", tag: "Adventure", image: steamHeaderImage(361420) },
  { title: "Atomic Heart", tag: "Action · Adventure", image: steamHeaderImage(668580) },
  { title: "Avowed", tag: "RPG", image: steamHeaderImage(2457220) },
  { title: "Bastion", tag: "Action · RPG", image: steamHeaderImage(107100) },
  { title: "Blasphemous", tag: "Action · Adventure", image: steamHeaderImage(774361) },
  { title: "Brotato", tag: "Action · Casual", image: steamHeaderImage(1942280) },
  { title: "Burnout Paradise Remastered", tag: "Action · Adventure", image: steamHeaderImage(1238080) },
  { title: "Captain of Industry", tag: "Simulation · Strategy", image: steamHeaderImage(1594320) },
  { title: "Cassette Beasts", tag: "RPG", image: steamHeaderImage(1321440) },
  { title: "Chained Echoes", tag: "RPG", image: steamHeaderImage(1229240) },
  { title: "Cities: Skylines II", tag: "Simulation", image: steamHeaderImage(949230) },
  { title: "Coffee Talk", tag: "Adventure · Casual", image: steamHeaderImage(914800) },
  { title: "Conan Exiles", tag: "Action · Adventure", image: steamHeaderImage(440900) },
  { title: "Content Warning", tag: "Action · Adventure", image: steamHeaderImage(2881650) },
  { title: "Coral Island", tag: "Adventure · Casual", image: steamHeaderImage(1158160) },
  { title: "Core Keeper", tag: "Action · Adventure", image: steamHeaderImage(1621690) },
  { title: "Coromon", tag: "Adventure · RPG", image: steamHeaderImage(1218210) },
  { title: "Cozy Grove", tag: "Casual", image: steamHeaderImage(1458100) },
  { title: "Craftopia", tag: "Action · Adventure", image: steamHeaderImage(1307550) },
  { title: "CrossCode", tag: "Action · Adventure", image: steamHeaderImage(368340) },
  { title: "Curse of the Dead Gods", tag: "Action · Adventure", image: steamHeaderImage(1123770) },
  { title: "Darksiders III", tag: "Action · Adventure", image: steamHeaderImage(606280) },
  { title: "Days Gone", tag: "Action · Adventure", image: steamHeaderImage(1259420) },
  { title: "DayZ", tag: "Action · Adventure", image: steamHeaderImage(221100) },
  { title: "Dead Space", tag: "Action · Adventure", image: steamHeaderImage(1693980) },
  { title: "Death's Door", tag: "Action · Adventure", image: steamHeaderImage(894020) },
  { title: "Deep Rock Galactic: Survivor", tag: "Action", image: steamHeaderImage(2321470) },
  { title: "Deltarune", tag: "RPG", image: steamHeaderImage(1671210) },
  { title: "Demonologist", tag: "Action · Adventure", image: steamHeaderImage(1929610) },
  { title: "Detroit: Become Human", tag: "Action · Adventure", image: steamHeaderImage(1222140) },
  { title: "Deus Ex: Human Revolution", tag: "Action · RPG", image: steamHeaderImage(238010) },
  { title: "Deus Ex: Mankind Divided", tag: "Action · RPG", image: steamHeaderImage(337000) },
  { title: "DEVOUR", tag: "Indie", image: steamHeaderImage(1274570) },
  { title: "Dinkum", tag: "Adventure · Casual", image: steamHeaderImage(1062520) },
  { title: "DIRT 5", tag: "Action · Adventure", image: steamHeaderImage(1038250) },
  { title: "Dishonored", tag: "Action · Adventure", image: steamHeaderImage(205100) },
  { title: "Disney Dreamlight Valley", tag: "Action · Adventure", image: steamHeaderImage(1401590) },
  { title: "Divinity: Original Sin 2", tag: "Adventure · RPG", image: steamHeaderImage(435150) },
  { title: "Don't Starve Together", tag: "Action · Adventure", image: steamHeaderImage(322330) },
  { title: "Dragon Age: Inquisition", tag: "Action · Adventure", image: steamHeaderImage(1222690) },
  { title: "Dungeons & Degenerate Gamblers", tag: "Casual · RPG", image: steamHeaderImage(2400510) },
  { title: "DUSK", tag: "Action", image: steamHeaderImage(519860) },
  { title: "Dyson Sphere Program", tag: "Simulation · Strategy", image: steamHeaderImage(1366540) },
  { title: "Elite Dangerous", tag: "Action · Adventure", image: steamHeaderImage(359320) },
  { title: "Endless Legend", tag: "RPG · Strategy", image: steamHeaderImage(289130) },
  { title: "Enshrouded", tag: "Action · Adventure", image: steamHeaderImage(1203620) },
  { title: "Enter the Gungeon", tag: "Action · Adventure", image: steamHeaderImage(311690) },
  { title: "Fallout 4", tag: "RPG", image: steamHeaderImage(377160) },
  { title: "Far Cry Primal", tag: "Action · Adventure", image: steamHeaderImage(371660) },
  { title: "First Class Trouble", tag: "Indie", image: steamHeaderImage(953880) },
  { title: "Forewarned", tag: "Action · Adventure", image: steamHeaderImage(1562420) },
  { title: "Frostpunk", tag: "Simulation · Strategy", image: steamHeaderImage(323190) },
  { title: "Gears Tactics", tag: "Strategy", image: steamHeaderImage(1184050) },
  { title: "Ghostrunner", tag: "Action", image: steamHeaderImage(1139900) },
  { title: "God Eater 3", tag: "Action", image: steamHeaderImage(899440) },
  { title: "Goose Goose Duck", tag: "Casual · Massively Multiplayer", image: steamHeaderImage(1568590) },
  { title: "Green Hell", tag: "Action · Adventure", image: steamHeaderImage(815370) },
  { title: "Griftlands", tag: "Indie", image: steamHeaderImage(601840) },
  { title: "Grim Dawn", tag: "Action · Adventure", image: steamHeaderImage(219990) },
  { title: "Gris", tag: "Adventure", image: steamHeaderImage(683320) },
  { title: "Grounded", tag: "Action · Adventure", image: steamHeaderImage(962130) },
  { title: "GTFO", tag: "Action", image: steamHeaderImage(493520) },
  { title: "Halls of Torment", tag: "Action · RPG", image: steamHeaderImage(2218750) },
  { title: "Hellblade: Senua's Sacrifice", tag: "Action · Adventure", image: steamHeaderImage(414340) },
  { title: "House Flipper", tag: "Action · Adventure", image: steamHeaderImage(613100) },
  { title: "Humankind", tag: "Strategy", image: steamHeaderImage(1124300) },
  { title: "Icarus", tag: "Action · Adventure", image: steamHeaderImage(1149460) },
  { title: "Immortals Fenyx Rising", tag: "Action · Adventure", image: steamHeaderImage(2221920) },
  { title: "Into the Breach", tag: "RPG · Simulation", image: steamHeaderImage(590380) },
  { title: "Jagged Alliance 3", tag: "Action · Strategy", image: steamHeaderImage(1084160) },
  { title: "Kenshi", tag: "Action · RPG", image: steamHeaderImage(233860) },
  { title: "Last Epoch", tag: "Action · Adventure", image: steamHeaderImage(899770) },
  { title: "Lies of P", tag: "Action · Adventure", image: steamHeaderImage(1627720) },
  { title: "Like a Dragon: Infinite Wealth", tag: "Action · Adventure", image: steamHeaderImage(2072450) },
  { title: "LISA: The Painful", tag: "Adventure · RPG", image: steamHeaderImage(335670) },
  { title: "Little Kitty, Big City", tag: "Adventure · Casual", image: steamHeaderImage(1177980) },
  { title: "Luck be a Landlord", tag: "Simulation · Strategy", image: steamHeaderImage(1404850) },
  { title: "Mafia: Definitive Edition", tag: "Action · Adventure", image: steamHeaderImage(1030840) },
  { title: "Manor Lords", tag: "Simulation · Strategy", image: steamHeaderImage(1363080) },
  { title: "Metaphor: ReFantazio", tag: "Action · Adventure", image: steamHeaderImage(2679460) },
  { title: "Metro Exodus", tag: "Action", image: steamHeaderImage(412020) },
  { title: "Mindustry", tag: "Strategy", image: steamHeaderImage(1127400) },
  { title: "Monster Hunter Rise", tag: "Action", image: steamHeaderImage(1446780) },
  { title: "Monster Sanctuary", tag: "Action · Adventure", image: steamHeaderImage(814370) },
  { title: "Monster Train", tag: "Strategy", image: steamHeaderImage(1102190) },
  { title: "Mortal Shell", tag: "Action · RPG", image: steamHeaderImage(1110910) },
  { title: "Mutant Year Zero: Road to Eden", tag: "RPG · Strategy", image: steamHeaderImage(760060) },
  { title: "My Time at Portia", tag: "Adventure · Casual", image: steamHeaderImage(666140) },
  { title: "My Time at Sandrock", tag: "Adventure · Casual", image: steamHeaderImage(1084600) },
  { title: "Need for Speed Heat", tag: "Action · Adventure", image: steamHeaderImage(1222680) },
  { title: "Neon White", tag: "Action · Adventure", image: steamHeaderImage(1533420) },
  { title: "Night in the Woods", tag: "Adventure", image: steamHeaderImage(481510) },
  { title: "Nioh 2", tag: "Action · RPG", image: steamHeaderImage(1325200) },
  { title: "Noita", tag: "Action · Adventure", image: steamHeaderImage(881100) },
  { title: "Nova Drift", tag: "Action", image: steamHeaderImage(858210) },
  { title: "Nuclear Throne", tag: "Action · RPG", image: steamHeaderImage(242680) },
  { title: "Okami HD", tag: "Adventure", image: steamHeaderImage(587620) },
  { title: "Old World", tag: "RPG · Simulation", image: steamHeaderImage(597180) },
  { title: "OMORI", tag: "Adventure · RPG", image: steamHeaderImage(1150690) },
  { title: "Overcooked! 2", tag: "Action · Casual", image: steamHeaderImage(728880) },
  { title: "Path of Exile", tag: "Action · Adventure", image: steamHeaderImage(238960) },
  { title: "Pathfinder: Wrath of the Righteous", tag: "Action · Adventure", image: steamHeaderImage(1184370) },
  { title: "Persona 4 Golden", tag: "RPG", image: steamHeaderImage(1113000) },
  { title: "Phoenix Point", tag: "RPG · Strategy", image: steamHeaderImage(839770) },
  { title: "Pillars of Eternity II: Deadfire", tag: "RPG", image: steamHeaderImage(560130) },
  { title: "Pillars of Eternity", tag: "RPG", image: steamHeaderImage(291650) },
  { title: "Planescape: Torment", tag: "Adventure · RPG", image: steamHeaderImage(466300) },
  { title: "Prey", tag: "Action · Adventure", image: steamHeaderImage(480490) },
  { title: "Prodeus", tag: "Action · Adventure", image: steamHeaderImage(964800) },
  { title: "Project Winter", tag: "Action · Adventure", image: steamHeaderImage(774861) },
  { title: "Rain World", tag: "Action · Adventure", image: steamHeaderImage(312520) },
  { title: "Remnant II", tag: "Action · Adventure", image: steamHeaderImage(1282100) },
  { title: "Resident Evil 2", tag: "Action", image: steamHeaderImage(883710) },
  { title: "Resident Evil Village", tag: "Action", image: steamHeaderImage(1196590) },
  { title: "Return of the Obra Dinn", tag: "Adventure", image: steamHeaderImage(653530) },
  { title: "Rise of the Ronin", tag: "Action · Adventure", image: steamHeaderImage(1340990) },
  { title: "Rogue Legacy 2", tag: "Action · Adventure", image: steamHeaderImage(1253920) },
  { title: "S.T.A.L.K.E.R.: Shadow of Chernobyl", tag: "Action · RPG", image: steamHeaderImage(4500) },
  { title: "Sable", tag: "Adventure · RPG", image: steamHeaderImage(757310) },
  { title: "Saints Row IV", tag: "Action · Adventure", image: steamHeaderImage(206420) },
  { title: "Satisfactory", tag: "Adventure · Simulation", image: steamHeaderImage(526870) },
  { title: "SCUM", tag: "Action · Adventure", image: steamHeaderImage(513710) },
  { title: "Sea of Stars", tag: "Adventure · RPG", image: steamHeaderImage(1244090) },
  { title: "Shadow Warrior 3", tag: "Action · Adventure", image: steamHeaderImage(1036890) },
  { title: "Shapez 2", tag: "Casual · Simulation", image: steamHeaderImage(2162800) },
  { title: "Sifu", tag: "Action", image: steamHeaderImage(2138710) },
  { title: "Skul: The Hero Slayer", tag: "Action", image: steamHeaderImage(1147560) },
  { title: "Sleeping Dogs: Definitive Edition", tag: "Action · Adventure", image: steamHeaderImage(307690) },
  { title: "Solasta: Crown of the Magister", tag: "Adventure · RPG", image: steamHeaderImage(1096530) },
  { title: "Sons of the Forest", tag: "Action · Adventure", image: steamHeaderImage(1326470) },
  { title: "Stanley Parable: Ultra Deluxe", tag: "Adventure · Casual", image: steamHeaderImage(1703340) },
  { title: "Star Wars Jedi: Fallen Order", tag: "Action · Adventure", image: steamHeaderImage(1172380) },
  { title: "Star Wars: Knights of the Old Republic", tag: "Adventure · RPG", image: steamHeaderImage(32370) },
  { title: "Starbound", tag: "Action · Adventure", image: steamHeaderImage(211820) },
  { title: "State of Decay 2", tag: "Action · RPG", image: steamHeaderImage(495420) },
  { title: "Stellaris", tag: "Simulation · Strategy", image: steamHeaderImage(281990) },
  { title: "Super Meat Boy", tag: "Indie", image: steamHeaderImage(40800) },
  { title: "Superliminal", tag: "Action · Adventure", image: steamHeaderImage(1049410) },
  { title: "System Shock", tag: "Action · Adventure", image: steamHeaderImage(482400) },
  { title: "Techtonica", tag: "Simulation · Strategy", image: steamHeaderImage(1457320) },
  { title: "Temtem", tag: "Adventure · Massively Multiplayer", image: steamHeaderImage(745920) },
  { title: "The Callisto Protocol", tag: "Action · Adventure", image: steamHeaderImage(1544020) },
  { title: "The Crew Motorfest", tag: "Racing", image: steamHeaderImage(2698940) },
  { title: "The Elder Scrolls V: Skyrim", tag: "RPG", image: steamHeaderImage(489830) },
  { title: "The Evil Within 2", tag: "Action · Adventure", image: steamHeaderImage(601430) },
  { title: "The Long Dark", tag: "Adventure · Simulation", image: steamHeaderImage(305620) },
  { title: "The Mortuary Assistant", tag: "Adventure · Simulation", image: steamHeaderImage(1295920) },
  { title: "The Outer Worlds", tag: "RPG", image: steamHeaderImage(578650) },
  { title: "The Talos Principle", tag: "Action · Adventure", image: steamHeaderImage(257510) },
  { title: "The Walking Dead: The Telltale Definitive Series", tag: "Adventure", image: steamHeaderImage(1449690) },
  { title: "The Witness", tag: "Adventure", image: steamHeaderImage(210970) },
  { title: "They Are Billions", tag: "Strategy", image: steamHeaderImage(644930) },
  { title: "Tiny Tina's Wonderlands", tag: "Action · Adventure", image: steamHeaderImage(1286680) },
  { title: "Titan Quest Anniversary Edition", tag: "Action · RPG", image: steamHeaderImage(475150) },
  { title: "To the Moon", tag: "Adventure · RPG", image: steamHeaderImage(206440) },
  { title: "Torchlight II", tag: "Action · Adventure", image: steamHeaderImage(200710) },
  { title: "Town of Salem 2", tag: "Action · Casual", image: steamHeaderImage(2140510) },
  { title: "Trek to Yomi", tag: "Action · Adventure", image: steamHeaderImage(1370050) },
  { title: "Tropico 6", tag: "Simulation · Strategy", image: steamHeaderImage(492720) },
  { title: "Tunic", tag: "Action · Adventure", image: steamHeaderImage(553420) },
  { title: "Two Point Campus", tag: "Casual · Simulation", image: steamHeaderImage(1649080) },
  { title: "ULTRAKILL", tag: "Action · Early Access", image: steamHeaderImage(1229490) },
  { title: "Unfortunate Spacemen", tag: "Action · Strategy", image: steamHeaderImage(408900) },
  { title: "Unpacking", tag: "Casual · Simulation", image: steamHeaderImage(1135690) },
  { title: "Unravel Two", tag: "Action · Adventure", image: steamHeaderImage(1225570) },
  { title: "V Rising", tag: "Action · Adventure", image: steamHeaderImage(1604030) },
  { title: "Vault of the Void", tag: "Strategy", image: steamHeaderImage(1135810) },
  { title: "Viewfinder", tag: "Adventure", image: steamHeaderImage(1382070) },
  { title: "Warhammer 40,000: Boltgun", tag: "Action", image: steamHeaderImage(2005010) },
  { title: "Warhammer: Vermintide 2", tag: "Action · RPG", image: steamHeaderImage(552500) },
  { title: "Wasteland 3", tag: "RPG · Strategy", image: steamHeaderImage(719040) },
  { title: "Watch Dogs 2", tag: "Action · Adventure", image: steamHeaderImage(447040) },
  { title: "What Remains of Edith Finch", tag: "Adventure", image: steamHeaderImage(501300) },
  { title: "Wild Hearts", tag: "Action · Adventure", image: steamHeaderImage(1938010) },
  { title: "Wo Long: Fallen Dynasty", tag: "Action · Adventure", image: steamHeaderImage(1448440) },
  { title: "Workers & Resources: Soviet Republic", tag: "Simulation · Strategy", image: steamHeaderImage(784150) },
];

function mergeDirectoryGamesUniqueSorted(
  primary: HomeGamePick[],
  extra: HomeGamePick[]
): HomeGamePick[] {
  const byKey = new Map<string, HomeGamePick>();
  for (const g of primary) {
    byKey.set(g.title.trim().toLowerCase(), g);
  }
  for (const g of extra) {
    const k = g.title.trim().toLowerCase();
    if (!byKey.has(k)) byKey.set(k, g);
  }
  return [...byKey.values()].sort((a, b) => a.title.localeCompare(b.title));
}

/**
 * Shuffled on the client for the homepage carousel — larger than `HOME_CAROUSEL_PICKS` alone.
 */
export const HOME_CAROUSEL_POOL: HomeGamePick[] = mergeDirectoryGamesUniqueSorted(
  HOME_CAROUSEL_PICKS,
  HOME_CAROUSEL_EXTRAS
);

/**
 * Alphabetical directory for /games — carousel picks plus curated extras.
 * Detail links use `gameDetailPath(title)` (RAWG resolves by search on first load).
 */
export const DIRECTORY_GAMES: HomeGamePick[] = mergeDirectoryGamesUniqueSorted(
  HOME_CAROUSEL_PICKS,
  EXTRA_DIRECTORY_GAMES
);
