import AppPageShell from "@/components/app/AppPageShell";
import AdminOnlyPageGate from "@/components/discovery/AdminOnlyPageGate";
import HiddenGemsView from "@/components/discovery/HiddenGemsView";
import { resolveRotation } from "@/lib/discovery/rotation-store";
import type { HiddenGemPick } from "@/lib/discovery/curated-picks";
import { buildPublicPageMetadata } from "@/lib/seo/site";
import type { Metadata } from "next";

export const metadata: Metadata = buildPublicPageMetadata({
  title: "Hidden gems worth discovering | GamePing AI",
  description:
    "Underrated games with a strong identity — discovery categories, a featured pick, and a curated grid of overlooked games beyond the usual recommendations.",
  path: "/hidden-gems",
});

// Read fresh on each request so a newly published rotation shows immediately;
// the data comes from the cached Supabase rotation (no RAWG/ITAD per visit).
export const dynamic = "force-dynamic";

// Admin-only while incomplete. The page reads the latest *published* rotation
// from Supabase (cached, generated by /api/admin/discovery/generate). Fallback
// order: current published rotation → latest published rotation → static list.
// Everyone except admins is blocked by AdminOnlyPageGate.
export default async function HiddenGemsPage() {
  const { data, meta } = await resolveRotation<HiddenGemPick>("hidden_gems");

  return (
    <AppPageShell hideAmbient>
      <div className="gp-accent-page relative isolate min-h-0 flex-1 overflow-hidden">
        {/* Fixed cinematic background — SAME image in light + dark. */}
        <div aria-hidden className="gp-hidden-gems-bg" />
        <AdminOnlyPageGate>
          <HiddenGemsView
            featured={data?.featured}
            picks={data?.picks}
            meta={meta ?? undefined}
          />
        </AdminOnlyPageGate>
      </div>
    </AppPageShell>
  );
}
