import AppPageShell from "@/components/app/AppPageShell";
import HiddenGemsView from "@/components/discovery/HiddenGemsView";
import { resolveRotation } from "@/lib/discovery/rotation-store";
import type { HiddenGemPick } from "@/lib/discovery/curated-picks";
import { buildPublicPageMetadata } from "@/lib/seo/site";
import type { Metadata } from "next";

export const metadata: Metadata = buildPublicPageMetadata({
  title: "Hidden gems worth discovering | GamePing AI",
  description:
    "Underrated games with a strong identity — discovery categories, a featured pick, and a curated grid of overlooked games beyond the usual recommendations.",
  path: "/hidden-gems",
});

// Read fresh on each request so a newly published rotation shows immediately;
// the data comes from the cached Supabase rotation (no RAWG/OpenAI per visit).
export const dynamic = "force-dynamic";

// Public page. Reads the cached *published* rotation from Supabase (generated by
// the discovery cron / admin route — never on a page visit). Fallback order:
// current published rotation → latest published rotation → static curated list.
export default async function HiddenGemsPage() {
  const { data, meta } = await resolveRotation<HiddenGemPick>("hidden_gems");

  return (
    <AppPageShell hideAmbient>
      <div className="gp-accent-page relative isolate min-h-0 flex-1 overflow-hidden">
        {/* Fixed cinematic background — SAME image in light + dark. */}
        <div aria-hidden className="gp-hidden-gems-bg" />
        <HiddenGemsView
          featured={data?.featured}
          picks={data?.picks}
          meta={meta ?? undefined}
        />
      </div>
    </AppPageShell>
  );
}
